google.maps.__gjsload__('geometry', function(_){var oqa=function(a,b){return Math.abs(_.ym(b-a,-180,180))},pqa=function(a,b,c,d,e){if(!d){c=oqa(a.lng(),c)/oqa(a.lng(),b.lng());if(!e)return e=Math.sin(_.Fl(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Fl(b.lat())),_.Gl(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.Qo(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Fl(a.lat());a=_.Fl(a.lng());d=_.Fl(b.lat());b=_.Fl(b.lng());c=_.Fl(c);return _.ym(_.Gl(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},qqa=function(a,b){a=new _.tn(a,!1);b=new _.tn(b,!1);return a.equals(b)},rqa=function(a,b,c){a=_.zn(a);c=c||1E-9;var d=_.ym(a.lng(),-180,180),e=b instanceof _.pu,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(let q=0,u=g.getLength();q<u;++q){let v=g.getAt(q),x=v.getLength(),y=e?x:x-1;for(let F=0;F<y;++F){var h=v.getAt(F);let I=v.getAt((F+1)%x);
if(qqa(h,a)||qqa(I,a))return!0;var k=_.ym(h.lng(),-180,180),m=_.ym(I.lng(),-180,180);let O=Math.max(k,m),L=Math.min(k,m);if(k=Math.abs(_.ym(k-m,-180,180))<=1E-9&&(Math.abs(_.ym(k-d,-180,180))<=c||Math.abs(_.ym(m-d,-180,180))<=c)){k=a.lat();m=Math.min(h.lat(),I.lat())-c;var p=Math.max(h.lat(),I.lat())+c;k=k>=m&&k<=p}if(k)return!0;if(O-L>180?d+c>=O||d-c<=L:d+c>=L&&d-c<=O)if(h=pqa(h,I,d,f,b),Math.abs(h-a.lat())<c)return!0}}return!1},sqa=function(a,b){var c=_.vn(a);a=_.wn(a);var d=_.vn(b);b=_.wn(b);return 2*
Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))},tqa=function(a,b,c){a=_.zn(a);b=_.zn(b);c=c||6378137;return sqa(a,b)*c},wqa=function(a,b){b=b||6378137;a instanceof _.Bp&&(a=a.getArray());a=(0,_.dt)(a);if(a.length===0)return 0;var c=Array(4),d=Array(3),e=[1,0,0,0],f=Array(3);uqa(a[a.length-1],f);for(let v=0;v<a.length;++v)uqa(a[v],d),MC(f,d,c),vqa(c,e,e),[f[0],f[1],f[2]]=d;var [g,h,k]=f,[m,p,q,u]=e;return 2*Math.atan2(g*p+h*q+k*u,m)*(b*b)},
xqa=function(a,b){if(isFinite(a)){var c=a%360;a=Math.round(c/90);c-=a*90;if(c===30||c===-30){c=Math.sign(c)*.5;var d=Math.sqrt(.75)}else c===45||c===-45?(c=Math.sign(c)*Math.SQRT1_2,d=Math.SQRT1_2):(d=c/180*Math.PI,c=Math.sin(d),d=Math.cos(d));switch(a&3){case 0:b[0]=c;b[1]=d;break;case 1:b[0]=d;b[1]=-c;break;case 2:b[0]=-c;b[1]=-d;break;default:b[0]=-d,b[1]=c}}else b[0]=NaN,b[1]=NaN},uqa=function(a,b){var c=Array(2);xqa(a.lat(),c);var [d,e]=c;xqa(a.lng(),c);var [f,g]=c;b[0]=e*g;b[1]=e*f;b[2]=d},
vqa=function(a,b,c){var d=a[0]*b[1]+a[1]*b[0]+a[2]*b[3]-a[3]*b[2],e=a[0]*b[2]-a[1]*b[3]+a[2]*b[0]+a[3]*b[1],f=a[0]*b[3]+a[1]*b[2]-a[2]*b[1]+a[3]*b[0];c[0]=a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3];c[1]=d;c[2]=e;c[3]=f},MC=function(a,b,c){var d=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2],g=a[0]+b[0],h=a[1]+b[1],k=a[2]+b[2],m=g*g+h*h+k*k,p=e*k-f*h;f=f*g-d*k;d=d*h-e*g;e=m*m+p*p+f*f+d*d;if(e!==0)b=Math.sqrt(e),c[0]=m/b,c[1]=p/b,c[2]=f/b,c[3]=d/b;else{a:for(m=[a[0]-b[0],a[1]-b[1],a[2]-b[2]],p=0;p<3;++p)if(m[p]!==
0){if(m[p]<0){m=[-m[0],-m[1],-m[2]];break a}break}p=0;for(f=1;f<m.length;++f)Math.abs(m[f])<Math.abs(m[p])&&(p=f);f=[0,0,0];f[p]=1;m=[m[1]*f[2]-m[2]*f[1],m[2]*f[0]-m[0]*f[2],m[0]*f[1]-m[1]*f[0]];p=Math.hypot(...m);m=[m[0]/p,m[1]/p,m[2]/p];p=Array(4);MC(a,m,p);a=Array(4);MC(m,b,a);vqa(a,p,c)}},XC=class{};XC.isLocationOnEdge=rqa;
XC.containsLocation=function(a,b){a=_.zn(a);var c=_.ym(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;var g=!1;for(let k=0,m=e.getLength();k<m;++k){let p=e.getAt(k);for(let q=0,u=p.getLength();q<u;++q){let v=p.getAt(q),x=p.getAt((q+1)%u);var h=_.ym(v.lng(),-180,180);let y=_.ym(x.lng(),-180,180),F=Math.max(h,y);h=Math.min(h,y);(F-h>180?c>=F||c<h:c<F&&c>=h)&&pqa(v,x,c,d,f)<a.lat()&&(g=!g)}}return g||rqa(a,b)};var YC=class{};YC.computeSignedArea=wqa;
YC.computeArea=function(a,b){if(!(a instanceof _.Bp||Array.isArray(a)||a instanceof _.Do||a instanceof _.Ep))try{a=_.Co(a)}catch(c){try{a=new _.Ep((0,_.Wea)(a))}catch(d){throw _.Wm("Invalid path passed to computeArea(): "+JSON.stringify(a));}}b=b||6378137;if(a instanceof _.Ep){if(a.getRadius()===void 0)throw _.Wm("Invalid path passed to computeArea(): Circle is missing radius.");if(a.getRadius()<0)throw _.Wm("Invalid path passed to computeArea(): Circle must have non-negative radius.");if(b<0)throw _.Wm("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");
if(a.getRadius()>Math.PI*b)throw _.Wm("Invalid path passed to computeArea(): Circle must not cover more than 100% of the sphere.");return 2*Math.PI*b**2*(1-Math.cos(a.getRadius()/b))}if(a instanceof _.Do){if(b<0)throw _.Wm("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");if(a.ij.lo>a.ij.hi)throw _.Wm("Invalid path passed to computeArea(): the southern LatLng of a LatLngBounds cannot be more north than the northern LatLng.");let c=2*Math.PI*b**2*(1-Math.cos((a.ij.lo-
90)*Math.PI/180));c-=2*Math.PI*b**2*(1-Math.cos((a.ij.hi-90)*Math.PI/180));return c*Math.abs(a.Ai.hi-a.Ai.lo)/360}return Math.abs(wqa(a,b))};YC.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.Bp&&(a=a.getArray());for(let d=0,e=a.length-1;d<e;++d)c+=tqa(a[d],a[d+1],b);return c};YC.computeDistanceBetween=tqa;YC.traversePath=function(){throw Error("traversePath() is not available in this version of the Maps JavaScript API.");};
YC.interpolate=function(a,b,c){a=_.zn(a);b=_.zn(b);var d=_.vn(a),e=_.wn(a),f=_.vn(b),g=_.wn(b),h=Math.cos(d),k=Math.cos(f);b=sqa(a,b);var m=Math.sin(b);if(m<1E-6)return new _.tn(a.lat(),a.lng());a=Math.sin((1-c)*b)/m;c=Math.sin(c*b)/m;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.tn(_.Gl(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Gl(Math.atan2(e,b)))};
YC.computeOffsetOrigin=function(a,b,c,d){a=_.zn(a);c=_.Fl(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.vn(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(f<0)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.wn(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.tn(_.Gl(g),_.Gl(a))};
YC.computeOffset=function(a,b,c,d){a=_.zn(a);b/=d||6378137;c=_.Fl(c);var e=_.vn(a);a=_.wn(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.tn(_.Gl(Math.asin(g)),_.Gl(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};YC.computeHeading=function(a,b){a=_.zn(a);b=_.zn(b);var c=_.vn(a),d=_.wn(a);a=_.vn(b);b=_.wn(b)-d;return _.ym(_.Gl(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)};var yqa={encoding:_.Ou,spherical:YC,poly:XC};_.ya.google.maps.geometry=yqa;_.bm("geometry",yqa);});
